/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thinh' at '3/28/17 3:44 PM' with Gradle 2.14.1
 *
 * @author thinh, @date 3/28/17 3:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
